### PR TITLE
Add in user-configurable auto-brightness level

### PR DESCRIPTION
**Pull request by strikeir13**
This is an attempt to add in the auto-brightness level editor as implemented in CM. (first git attempt and first android contribution overall, so any feedback whatsoever is greatly appreciated...)

### CODE REVIEW

**Comment by Zaphod-Beeblebrox** [comment]
Having looked at the CM code .. this only implements the settings side.  I think there will still be framework changes needed to implement the settings.
I'll do some searching and see what it will take to actually make the settings functional inside the framework.

**Comment by strikeir13** [comment]
I've attempted to add the framework changes needed to implement these settings. The pull request can be found here:

https://github.com/AOKP/frameworks_base/pull/44

Let me know if there is more that needs to be changed, but I'm hoping that's it.

**Comment by LorDClockaN** [comment]
you are missing this:
https://github.com/IceColdSandwich/android_packages_apps_Settings/commit/04539ca24f36440656fb0fbd5c8d718b785a6ed3

**Comment by LorDClockaN** [comment]
the settings doesn't show anywhere under Settings menu
so I added this:
https://github.com/IceColdSandwich/android_packages_apps_Settings/commit/98814aa6d2008ae9fcc1007710aede1ac2382d7d
still not tested, but will let you know in about 10-15mins

**Comment by LorDClockaN** [comment]
settings FCs.. will try to fix, but the option shows up

**Comment by LorDClockaN** [comment]
crap! I just noticed that your LightLevelsActivity.java is an Activity
you need to make it a Fragment...

good night

**Comment by strikeir13** [comment]
Unfortunately, I don't know how to change an Activity into a Fragment. My commits so far have been copy/paste endeavors.

I'd like to know how to do that, but it probably won't happen anytime soon, so I would greatly appreciate some outside help in this instance.

**Comment by Rdlgrmpf** [comment]
Currently trying to convert Init.d into a fragment. Not sure if it even compiles yet, but I had a look at "Performance" and what changed there.
Activity:
https://github.com/AOKP/packages_apps_ROMControl/blob/master/src/com/roman/romcontrol/tools/Performance.java
Fragment
https://github.com/AOKP/packages_apps_ROMControl/blob/master/src/com/roman/romcontrol/fragments/Performance.java

**Comment by Zaphod-Beeblebrox** [comment]
LightLevels does not need to be turned into a Fragment....
We need a little code inside the settings to initiate(call)  the lightLevelsActivity as a seperate app...
it might be nice to re-write it one day as a fragment, so it looks nicer on tablets, but on phones it won't much matter.
I just started toying with this code last night, but I think I might have enough to get this working now...
I'll update/push once its working.

**Comment by Zaphod-Beeblebrox** [comment]
turns out you were missing a good portion of this.  LightLevelsActivity is just the app that lets you put in custom threshold values.  BackLight.java is the PreferencesFragment that lets you turn on the custom levels and loads LightLevels when needed...
I've gotten all of that integrated into Settings now, but the actual 'LightLevelsActivity' is crashing when it tries to getLightSensorValue from PowerManager,   Trying to figure out now if we are missing something over on the frameworks side.

**Comment by Zaphod-Beeblebrox** [comment]
OK ... I got it working.   I ended up sending a new/separate pull request, but all of the participants here are getting credit on their commits.
Thanks guys!

**Pull request merged**
